### ISSUE TITLE
Unable to parse module during webpack build

### ISSUE THREAD

**Issue by geeogi** [aeroheim/audio-file-decoder#1]
Hi there, thanks a lot for creating this module. I'm hoping to use it as an alternative to the web audio `.decodeAudioData` to reduce memory consumption in my app. 

I'm struggling to get babel to load the JS for this module during my webpack build for my React app. It keeps spitting out this error: 

```
./node_modules/audio-file-decoder/dist/audio-file-decoder.js 34:19
Module parse failed: Unexpected token (34:19)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| var R,
>     s = (R = import.meta.url, function (U) {
|   var Q, B, i;
|   U = U || {}, Q || (Q = void 0 !== U ? U : {}), Q.ready = new Promise(function (F, U) {
```

I assumed it was the `import.meta.url`, so I added the `@babel/plugin-syntax-import-meta` plugin. Didn't make a difference. My webpack is using `file-loader`, so I assume it should be able to bundle the `.wasm` file OK (?)

Any ideas what might be going wrong here? Appreciate any guidance or pointers.

**Comment by aeroheim** [comment]
What babel presets are you using? Also what babel/webpack versions? Based on the error message you included it seems like babel choked while trying to parse the js side of the lib and might not have gotten to the wasm yet.

I tested real quick with webpack 5, `babel-loader` and `@babel/preset-env` and it seems to work.

**Comment by geeogi** [comment]
Yes it does seem like it's having trouble with the JS. I'm using:

webpack: 4.44.2
babel-loader: 8.1.0
@babel/core: 7.12.3

Babel preset is `babel-preset-react-app` which is based on `preset-env`: https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/dependencies.js (this is the default configuration for Create React App: https://github.com/facebook/create-react-app). 

Here is a code sandbox where I've taken the CRA base project and imported audio-file-decoder: https://codesandbox.io/s/create-react-app-forked-r3h2y?file=/src/App.js

**Comment by aeroheim** [comment]
Wow, trying to use custom webpack configs in codesandbox was certainly an exercise in frustration. 🤦 Anyways, here's a [codesandbox](https://codesandbox.io/s/bold-shannon-h3xcc) that should work. It runs on webpack 5 since codesandbox *really* didn't want me using webpack 4, but if it's a requirement you could probably get it working with a few minor tweaks much faster on a local dev server or something.

A few things to note:
- the example is a minimal setup that doesn't use CRA. I don't really use CRA so I'm not sure how their webpack configs work, plus it looked pretty painful trying to eject and tweak it all on codesandbox.
- you'll want to use `type: "javascript/auto"` on `file-loader`, otherwise webpack will try to parse the .wasm file contents which it obviously can't and choke. see https://github.com/webpack/webpack/issues/6725.
- also need to enable either the `syncWebAssembly` or `asyncWebAssembly` flags. see https://webpack.js.org/configuration/experiments/
- there's probably something funky with codesandbox's environment since webpack 5 was complaining about missing node modules polyfills that the lib apparently requires. you should be able to safely ignore them like I did in the webpack config, although I haven't had to do so when I tested on local dev servers.

Let me know if this helps.

**Comment by geeogi** [comment]
Thanks a lot for taking a look. I've migrated my build from webpack 4 to webpack 5 using your config and it's now working for me!
