### ISSUE TITLE
Can you expose the API that decoding arraybuffer directly?

### ISSUE THREAD

**Issue by asurance** [aeroheim/audio-file-decoder#2]
Can you expose the API that decoding arraybuffer directly?

**Comment by aeroheim** [comment]
Maybe - I'm not against exposing it, but I would like to know what your use case is. For browser environments it shouldn't be an issue since you can already convert between ArrayBuffer and File objects.

**Comment by asurance** [comment]
I want to develop an extension for `vscode` to preview audio file so that I want to decode audio file in `nodejs` environment. In `nodejs` environment, `wasm` can be loaded once for decoding many files (I noticed that it's size is more than 1MB)and I can cache the result for files.

**Comment by aeroheim** [comment]
Supporting node environments is a non-trivial task. The library relies on parts of the browser API (web workers and FileReader), so there would be need to be a new node export that either polyfills or replaces them with node alternatives. 

In terms of the changes needed, FileReader isn't an issue since the API can be changed to support ArrayBuffers, but the worker implementation would need to be re-written to use node's `worker_threads` module. The wasm build process also injects additional glue code into the worker source code to codegen the final worker implementation, so it needs be updated as well.

If you are able to submit a PR with an implementation and are willing to test it then I'd be happy to take a look. Otherwise I don't really have the bandwidth to expand the scope of this library. For alternatives, if you really need a solution that works in node you can always create your own native node module that uses FFmpeg's API to decode. It would be faster and less memory intensive than this library since it can run natively instead of in the browser.

**Comment by asurance** [comment]
Actually, I tried to use `ffmpeg.wasm` before. But it used dynamic import so that I can't bundle file correctly using `webpack` and its size is bigger than 11MB. I don't want my extension to so big for downloading or loading. Also, my extension can't rely on `ffmpeg` for I can't make sure user's environment has it or force them to install it. I found that what I need exactly is `wasm` and it's glue code. I can get `wasm` in release package while glue code has been bundled. So I tried to compile wasm by myself using steps that you provided in `Readme.md` with `Docker`. Howerer, errors always happen when I run `npm run build-deps` such as `ERROR: libmp3lame >= 3.98.3 not found`. Is there some dependencies that you forgot to mention in `Readme.md`.

**Comment by aeroheim** [comment]
Did `npm run sync` succeed without any issues? It downloads/clones all of FFmpeg's required dependencies including `libmp3lame`. Afterwards `npm run build-deps` should compile the dependencies and then compile FFmpeg itself.

The `ERROR: libmp3lame >= 3.98.3 not found` probably means `pkgconfig` (used by FFmpeg) isn't detecting the compiled `libmp3lame`. Unfortunately it's not very descriptive about what the actual issue is - you might want to check the [makefile](../blob/master/makefile) and try debugging from there (e.g try removing `--enable-libmp3lame` from FFmpeg's compilation and see if `pkgconfig` can still resolve the other dependencies like `libopus`). There might be an issue with your container's environment.

**Comment by asurance** [comment]
I removed `libmp3lame` and compile again and it throws `opus not found using pkg-config`. I think if there are a few steps about change the working directory missing before `build-deps`. For now, I run all scripts in the root directory.

**Comment by asurance** [comment]
OK, I gave up. It's too hard for me to compile the `wasm`. I tried to use `audio-file-decoder` in `webview`. It seems to be OK. Anyway, thank you for help. 😄
