### ISSUE TITLE
File decoding breaks on larger mp3s

### ISSUE THREAD

**Issue by amcjen** [aeroheim/audio-file-decoder#4]
Hey there, really loving this module so far--it's really nice to get encoding/bitrate data from various audio files!

I'm finding an issue with decoding larger mp3s, however. I have several large podcast mp3s and the decoding is failing on them.

I've narrowed it down to the maximum size the decoder is able to process to be 3043 seconds (i.e. `decoder.decodeAudioData(0, 3043)`.  Kicking it up to 3044 and it errors out. 

This happens regardless of `multiChannel` being set to true or false.

The error I get in the console is: 

```
RuntimeError: Aborted(). Build with -s ASSERTIONS=1 for more info.
    at bi (audio-file-decoder.js:1:5435)
    at a (audio-file-decoder.js:1:54347)
    at decode-audio.wasm:0x24c9
    at decode-audio.wasm:0x8a032
    at decode-audio.wasm:0xa2341
    at decode-audio.wasm:0xba527
    at Object.decodeAudio (eval at <anonymous> (audio-file-decoder.js:1:40511), <anonymous>:11:10)
    at n2.value (audio-file-decoder.js:1:64801)
    at waveform.ts:54:31
    at async sendSuccessEvent (AudioFileUploader.vue:130:31)
```

I started going down the road of trying different emscripten versions (everything between 3.0.0 and 3.1.24), but no changes to the issue. I did not try different versions of ffmpeg.

I also attempted to enable `ASSERTIONS=1` in emscripten, along with other compiler settings (removing `-O`, and trying `-g3`, `-gsource-map`, `SAFE_HEAP=1`, and `STACK_OVERFLOW_CHECK=1` and then enabling the Chrome Dev Tools DWARF debugger--but I wasn't able to get audio-file-decoder to load correctly.  

Admittedly, I'm likely bumping up against the limits of my understanding of the innards of how webworkers/wasm/emscripten works.

To reproduce, any mp3 file that's longer than 3043 seconds exhibits this behavior for me. Happy to provide a file to test, or just grabbing any public podcast episode will likely do the trick.

I realize decoding these huge files just might be out of scope for this project, as even on my fast M1 Mac, it takes ~16 seconds to decode the 3043 seconds--which is not a great user experience. I recognize this may be a will-not-fix response, but wanted to bring it to your attention anyhow.

**Comment by aeroheim** [comment]
Thanks for the detailed notes regarding the issue - helped me to narrow it down pretty fast!

From a quick test on Chrome I saw the following:
`Cannot enlarge memory, asked to go up to 2154847376 bytes, but the limit is 2147483648 bytes!`

So it looks like the root issue is that the internal wasm heap that holds the decoded data is trying to grow past the default [limit](https://v8.dev/blog/4gb-wasm-memory#:~:text=Thanks%20to%20recent%20work%20in,512MB%20or%201GB%20of%20memory!) of 2GB. 

Assuming typical recording formats (44.1khz, stereo, floating point samples), 3044 seconds should only be around ~1074MB (and this lib should be adding very little overhead), so I suspect there are some quirks with the internal heap management logic or emscripten that caused it to allocate prematurely past the limit for some reason. 

I can bump up the memory limit to 4GB which will fix this instance of the issue, but keep in mind a hard limit will still exist. As a general note though I recommend decoding audio data in chunks instead of all at once - it can be really expensive in terms of performance and memory which is why the library exists 😄

**Comment by amcjen** [comment]
Thanks for the quick reply! I figured I was bumping up against the practical limits of what's possible within the sandbox.

Super weird that emscripten is allocating that much memory. The one it failed on for me was a mono 16 bit/44.1k podcast, and the number of seconds seemed to be consistent regardless of mono/stereo/bit rate/sample rate.

Definitely will consider splitting up the decoding, you made it super easy to do it in chunks--so this shouldn't be a problem. 

Thanks again!
